security:
    ignored: =/**
    basic:
      enable: false

server:
  port: ${port}

spring:
    datasource:
        username: bdea7a11ee3082
        password: 6138a6c7
        url: jdbc:mysql://us-cdbr-iron-east-04.cleardb.net:3306/heroku_f667d96c66e3f1b?nullNamePatternMatchesAll=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&createDatabaseIfNotExist=true&serverTimezone=Asia/Bangkok&useTimezone=true&reconnect=true
        driverClassName: com.mysql.cj.jdbc.Driver