version: '2'
services:
  db:
    container_name: eventrock-bookkeeper
    image: mysql:5.7.13
    environment:
      TZ: 'Asia/Bangkok'
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bookkeeper
      MYSQL_USER: eventrock
      MYSQL_PASSWORD: mysecretpassword
    ports:
      - "3306:3306"
